services:

  postgres:
    image: postgres:17
    container_name: opencampus-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: opencampus
      POSTGRES_PASSWORD: opencampus
      POSTGRES_DB: opencampus

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U opencampus"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    container_name: opencampus-redis
    restart: unless-stopped

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data


volumes:

  postgres_data:
  redis_data:
